CREATE OR REPLACE FUNCTION FRED_INDEX_DATA.HARMONIZED_DOW30.NORMALIZE_EXCHANGE_RATE(rate FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
    CASE
        WHEN rate IS NULL THEN 1.0
        WHEN rate <= 0 THEN 1.0
        ELSE rate
    END
$$;
