CREATE OR REPLACE PROCEDURE FRED_INDEX_DATA.RAW_DOW30.LOAD_RAW_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Copy data from the stage into the raw staging table
    COPY INTO FRED_INDEX_DATA.RAW_DOW30.RAW_DOW30_STAGING 
    FROM @FRED_INDEX_DATA.RAW_DOW30.FRED_DATA_STAGE 
    FILE_FORMAT = (FORMAT_NAME = 'FRED_INDEX_DATA.RAW_DOW30.CSV_FORMAT') 
    ON_ERROR = 'CONTINUE';

    -- Return success message
    RETURN 'Data loaded successfully from stage';
END;
$$;






