-- Create analytics tables
CREATE OR REPLACE TABLE FRED_INDEX_DATA.ANALYTICS_DOW30.DAILY_PERFORMANCE (
    DATE DATE,
    INDEX_NAME STRING,
    VALUE FLOAT,
    DAILY_RETURN FLOAT,
    VOLATILITY FLOAT,
    PRIMARY KEY (DATE, INDEX_NAME)
);

CREATE OR REPLACE TABLE FRED_INDEX_DATA.ANALYTICS_DOW30.WEEKLY_PERFORMANCE (
    WEEK_START DATE,
    INDEX_NAME STRING,
    AVG_VALUE FLOAT,
    WEEKLY_RETURN FLOAT,
    VOLATILITY FLOAT,
    PRIMARY KEY (WEEK_START, INDEX_NAME)
);

