-- Create tasks for automation
CREATE OR REPLACE TASK FRED_INDEX_DATA.RAW_DOW30.LOAD_DOW30_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 0 * * * America/New_York'
AS
CALL FRED_INDEX_DATA.RAW_DOW30.LOAD_RAW_DATA();

CREATE OR REPLACE TASK FRED_INDEX_DATA.RAW_DOW30.UPDATE_DOW30_METRICS_TASK
WAREHOUSE = COMPUTE_WH
AFTER FRED_INDEX_DATA.RAW_DOW30.LOAD_DOW30_TASK
AS
CALL FRED_INDEX_DATA.HARMONIZED_DOW30.UPDATE_DAILY_INDEX_METRICS();

-- Create harmonization task
CREATE OR REPLACE TASK FRED_INDEX_DATA.HARMONIZED_DOW30.HARMONIZE_DATA_TASK
WAREHOUSE = COMPUTE_WH
AFTER FRED_INDEX_DATA.RAW_DOW30.UPDATE_DOW30_METRICS_TASK
AS
CALL FRED_INDEX_DATA.HARMONIZED_DOW30.RUN_HARMONIZATION();

-- Activate tasks
ALTER TASK FRED_INDEX_DATA.HARMONIZED_DOW30.HARMONIZE_DATA_TASK RESUME;
ALTER TASK FRED_INDEX_DATA.RAW_DOW30.UPDATE_DOW30_METRICS_TASK RESUME;
ALTER TASK FRED_INDEX_DATA.RAW_DOW30.LOAD_DOW30_TASK RESUME;

