[my_default_connection]
account = "your_account_name"
user = "your_username"
password = "your_password"
warehouse = "your_warehouse_name"
database = "your_database_name"
schema = "your_schema_name"
role = "your_role_name"
