name: Deploy Snowpark Python Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      - name: Configure default connection
        run: |
          mkdir -p .snowflake
          cat <<EOF > .snowflake/config.toml
          [default_connection_name]
          default_connection_name = "my_default_connection"

          [connections]
          [connections.my_default_connection]
          account = "${SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT}"
          user = "${SNOWFLAKE_CONNECTIONS_DEFAULT_USER}"
          password = "${SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD}"
          warehouse = "${SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE}"
          database = "${SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE}"
          role = "${SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE}"
          EOF

      - name: Test Snowflake connection
        run: |
          snowsql -q "SELECT CURRENT_TIMESTAMP;"

      - name: Fetch repository changes
        run: |
          snow git fetch my_git_repo

      - name: Deploy scripts to Snowflake
        run: |
          snowsql -q "CREATE OR REPLACE PROCEDURE demo_db.git_demo.filter_table(
            inputTableName VARCHAR,
            filter_value VARCHAR,
            outputTableName VARCHAR
          ) RETURNS STRING 
          LANGUAGE PYTHON 
          RUNTIME_VERSION = '3.9' 
          PACKAGES = ('snowflake-snowpark-python') 
          IMPORTS = ('@admin_db.integrations.snowflake_snowpark_utilities/branches/main/common/filter_table.py') 
          HANDLER = 'filter_table.main';"
