name: Deploy Demo Objects

# Controls when the action will run. 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python environment
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Python packages
      - name: Install Python packages
        run: pip install -r requirements.txt

      # Step 4: Replace placeholders in SQL script
      - name: Replace placeholders in SQL script
        run: |
          sed -i "s|\${S3_PATH}|${{ secrets.S3_PATH }}|g" scripts/02_snowflake_setup.sql
          sed -i "s|\${AWS_ACCESS_KEY_ID}|${{ secrets.AWS_ACCESS_KEY_ID }}|g" scripts/02_snowflake_setup.sql
          sed -i "s|\${AWS_SECRET_ACCESS_KEY}|${{ secrets.AWS_SECRET_ACCESS_KEY }}|g" scripts/02_snowflake_setup.sql

      # Step 5: Deploy Snowflake objects (SQL scripts)
      - name: Deploy Snowflake objects
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          snow sql -f scripts/02_snowflake_setup.sql --temporary-connection \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --role $SNOWFLAKE_ROLE \
            --warehouse $SNOWFLAKE_WAREHOUSE

      # Step 6: Deploy Snowpark Python scripts (UDFs and procedures)
      - name: Deploy Snowpark Python scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          python scripts/deploy_snowpark.py

      # Step 7 (Optional): Run unit tests
      - name: Run unit tests
        if: always()  # Run even if previous steps fail
        run: |
          if [ -d "test" ]; then
            pip install pytest
            pytest test/
          else
            echo "No test directory found, skipping tests"
          fi
